"""Deterministic two-layer header builder (09 §D · BUILD CONTRACT (d)) ★.

This is the **only place** chunk headers are produced, so they never drift
(governance requirement 09 §D-3). Every chunk's embedded ``text`` is::

    <L1 인용헤더>
    <L2 맥락헤더>
    <정규화된 본문>

Both header layers are generated by **rule/template — never by an LLM** (cost
rule: header context is deterministic and $0). The L2 context line is composed
from the parent title + structural position + key entities (소관부처 / 지자체 /
사건종류) already present in the parsed document; no model call, no token spend.

The single public entry point is :func:`build_headers`::

    embed_text, payload = build_headers(doc, article)

where ``doc`` is a parsed :class:`ingest.schema.Document` (as a dict) and
``article`` is one of its ``articles`` (a dict with ``article_no``, ``title``,
``text``). ``embed_text`` is the normalized two-layer-header + body string that
``embed/chunk.py`` embeds; ``payload`` is the structured meta dict (09 §D-2)
stored alongside the vector. The body is normalized for embedding (09 §B-4)
while the original is preserved by the caller for citation / source-pack.

Owner: header builder. Imports shared constants from ``config`` and the header
schema; defines no model/dimension/path constants of its own.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Any, Final

import config
from header.schema import PAYLOAD_REQUIRED

# --------------------------------------------------------------------------- #
# doc_type → Korean display label used in the L1 bracket tag.                  #
# --------------------------------------------------------------------------- #
_DOC_TYPE_LABEL: Final[dict[str, str]] = {
    "law": "법령",
    "ordinance": "자치법규",
    "admrule": "행정규칙",
    "precedent": "판례",
}

# Human-readable kind word for the L2 context sentence (falls back to the law
# name's own kind, e.g. "법률"/"시행령"/"조례"/"훈령").
_DOC_TYPE_NOUN: Final[dict[str, str]] = {
    "law": "법령",
    "ordinance": "자치법규",
    "admrule": "행정규칙",
    "precedent": "판례",
}

# --------------------------------------------------------------------------- #
# Normalization (09 §B-4) — applied to the EMBEDDING text only. The caller     #
# keeps the original article text for citation / source-pack.                  #
# --------------------------------------------------------------------------- #

# Circled numerals ①..⑳ -> "(1)".."(20)" (병기 형태로 검색 노이즈↓, 항 식별↑).
_CIRCLED: Final[dict[str, str]] = {
    chr(0x2460 + i): f"({i + 1})" for i in range(20)
}
_CIRCLED_RE: Final[re.Pattern[str]] = re.compile(
    "|".join(re.escape(c) for c in _CIRCLED)
)

# Amendment annotations such as ``<개정 2016. 1. 22.>`` / ``<신설 ...>`` /
# ``<전문개정 ...>``: stripped from the embedding body (search noise) and
# surfaced in payload["amendments"] instead (09 §B-4). Handles both ASCII and
# fullwidth angle brackets.
_AMEND_RE: Final[re.Pattern[str]] = re.compile(
    r"[<＜]\s*(개정|신설|전문개정|본조신설|본항신설|단서신설|제목개정)"
    r"[^>＞]*[>＞]"
)

# Precedent de-identification: collapse runs of the masking glyph (○ / ㅇ) used
# for anonymized party names into a single ``[당사자]`` token (09 §B-4).
_PARTY_RE: Final[re.Pattern[str]] = re.compile(r"[○ㅇ]{2,}")

# Collapse whitespace runs to single spaces within a single rendered line.
_WS_LINE_RE: Final[re.Pattern[str]] = re.compile(r"[ \t ]+")
# Collapse 3+ newlines down to a paragraph break.
_WS_BLOCK_RE: Final[re.Pattern[str]] = re.compile(r"\n{3,}")


def extract_amendments(text: str) -> list[str]:
    """Return the amendment annotations found in ``text`` (09 §B-4).

    Args:
        text: Raw article/section body.

    Returns:
        A list of the matched ``<개정 …>`` / ``<신설 …>`` strings, in order of
        appearance, with surrounding whitespace trimmed. Empty if none.
    """
    if not text:
        return []
    return [m.group(0).strip() for m in _AMEND_RE.finditer(text)]


def normalize_body(text: str) -> str:
    """Normalize an article/section body for **embedding** (09 §B-4).

    Steps, in order: Unicode NFC → circled numerals to ``(n)`` → strip amendment
    annotations → collapse anonymization glyphs to ``[당사자]`` → tidy
    whitespace. The original text is *not* mutated (the caller passes a copy and
    preserves the original for citation / source-pack).

    Args:
        text: Raw body text.

    Returns:
        The normalized embedding-text body (may be empty if ``text`` was empty).
    """
    if not text:
        return ""
    out = unicodedata.normalize("NFC", text)
    out = _CIRCLED_RE.sub(lambda m: _CIRCLED[m.group(0)], out)
    out = _AMEND_RE.sub("", out)
    out = _PARTY_RE.sub("[당사자]", out)
    # Tidy whitespace line by line, then collapse excessive blank lines.
    out = "\n".join(_WS_LINE_RE.sub(" ", ln).strip() for ln in out.splitlines())
    out = _WS_BLOCK_RE.sub("\n\n", out).strip()
    return out


# --------------------------------------------------------------------------- #
# Entity helpers — pull "key entities" out of the parsed Document for the L2    #
# context line. All deterministic; tolerant of the varied raw shapes (소관부처   #
# may be a list, 지자체구분 a nested dict, etc.).                                #
# --------------------------------------------------------------------------- #


def _clean(value: Any) -> str:
    """Coerce a possibly-None / list / scalar meta value to a tidy string.

    Args:
        value: A front-matter value (str, list, None, ...).

    Returns:
        A single-line string; first element if a list; ``""`` for None/empty.
    """
    if value is None:
        return ""
    if isinstance(value, (list, tuple)):
        for item in value:
            s = _clean(item)
            if s:
                return s
        return ""
    if isinstance(value, dict):
        # e.g. 지자체구분 {광역, 기초}: prefer the wide-area name.
        for key in ("광역", "name", "기초"):
            if value.get(key):
                return _clean(value[key])
        return ""
    return _WS_LINE_RE.sub(" ", str(value)).strip()


def _competent_authority(doc: dict[str, Any]) -> str:
    """Return the owning ministry / local government / court for the L2 line.

    Picks the most specific entity available for the doc_type: 소관부처 (law),
    지자체기관명/jurisdiction (ordinance), 소관부처명 (admrule), 법원명/
    jurisdiction (precedent).

    Args:
        doc: Parsed Document dict.

    Returns:
        The entity name, or ``""`` if none is recorded.
    """
    meta = doc.get("meta") or {}
    doc_type = doc.get("doc_type")
    if doc_type == "law":
        return _clean(meta.get("소관부처")) or _clean(doc.get("jurisdiction"))
    if doc_type == "admrule":
        return _clean(meta.get("소관부처명")) or _clean(doc.get("jurisdiction"))
    if doc_type == "ordinance":
        return _clean(meta.get("지자체기관명")) or _clean(doc.get("jurisdiction"))
    # precedent: the court.
    return _clean(doc.get("jurisdiction")) or _clean(meta.get("법원명"))


def _gov_level(doc: dict[str, Any]) -> str:
    """Return the ordinance government level (``광역`` | ``교육청`` | ``기초``).

    Reads the parser-derived ``meta['gov_level']`` when present (the authoritative
    classification from ``ingest.parse_ordinance``). Falls back to inferring from
    the raw ``meta['기초']`` sentinel (``_본청``/``_교육청`` ⇒ 광역/교육청; any other
    value ⇒ 기초) so headers stay correct even for payloads built before the
    classification was added. Returns ``""`` for non-ordinance documents.

    Args:
        doc: Parsed Document dict.

    Returns:
        The level string, or ``""`` when unknown / not an ordinance.
    """
    if doc.get("doc_type") != "ordinance":
        return ""
    meta = doc.get("meta") or {}
    level = _clean(meta.get("gov_level"))
    if level:
        return level
    basic = _clean(meta.get("기초"))
    if not basic:
        return "광역"
    if basic == "_본청":
        return "광역"
    if basic == "_교육청":
        return "교육청"
    return "기초"


def _locality(doc: dict[str, Any]) -> str:
    """Return the specific 기초 단체 name (구/시/군) for an ordinance, else ``""``.

    Prefers the parser-derived ``meta['locality']``; falls back to the raw
    ``meta['기초']`` unless it is a 광역/교육청 sentinel.
    """
    if doc.get("doc_type") != "ordinance":
        return ""
    meta = doc.get("meta") or {}
    loc = _clean(meta.get("locality"))
    if loc:
        return loc
    basic = _clean(meta.get("기초"))
    if basic and basic not in ("_본청", "_교육청"):
        return basic
    return ""


def _chapter_path(article: dict[str, Any], doc: dict[str, Any]) -> str | None:
    """Return the chapter/section path for the L1 position, if known.

    The parsers may attach a ``chapter`` / ``chapter_path`` field to an article
    (e.g. "제2장") when they track headings; this is optional. When absent the
    L1 line simply omits the chapter segment.

    Args:
        article: The article dict.
        doc: The owning document dict.

    Returns:
        A chapter path string (e.g. "제2장") or ``None``.
    """
    for key in ("chapter_path", "chapter", "장"):
        val = _clean(article.get(key)) if isinstance(article, dict) else ""
        if val:
            return val
    return None


# --------------------------------------------------------------------------- #
# L1 (citation) header.                                                         #
# --------------------------------------------------------------------------- #


def build_l1(doc: dict[str, Any], article: dict[str, Any]) -> str:
    """Build the L1 citation header line (09 §D-1).

    Legal text form::

        [법령] 도로교통법 > 제2장 > 제17조(자동차등의 속도) · 시행 2026-04-02 · 소관 경찰청

    Precedent form::

        [판례] 대법원 2022-05-25 2022누50008 · 선거·특별 · 판결요지

    The line is deterministic and contains the doc_type's required identifiers
    (law name / case info, article/section, effective/decision date) so that a
    citation is self-sufficient and the validator can confirm them by substring.

    Args:
        doc: Parsed Document dict (provides title, type, dates, entities).
        article: The article/section dict (``article_no``, optional ``title``).

    Returns:
        A single-line L1 header string.
    """
    doc_type = str(doc.get("doc_type") or "")
    tag = _DOC_TYPE_LABEL.get(doc_type, "문서")
    title = _clean(doc.get("title"))
    article_no = _clean(article.get("article_no"))
    article_title = _clean(article.get("title"))
    effective = _clean(doc.get("effective_from"))

    if doc_type == "precedent":
        # [판례] {법원} {선고일} {사건번호} · {사건종류} · {섹션}
        meta = doc.get("meta") or {}
        court = _clean(doc.get("jurisdiction")) or _clean(meta.get("법원명"))
        case_no = _clean(meta.get("사건번호"))
        case_kind = _clean(doc.get("law_kind")) or _clean(meta.get("사건종류"))
        head = " ".join(p for p in (court, effective, case_no) if p)
        segs = [f"[{tag}] {head}".rstrip()]
        if case_kind:
            segs.append(case_kind)
        # The precedent "article_no" is the section name (판결요지 / 판례내용 …).
        if article_no:
            segs.append(article_no)
        return " · ".join(segs)

    # Legal text: [법령] {법령명} > {장} > {제N조(제목)} · 시행 {시행일} · 소관 {부처}
    position = article_no
    if article_title:
        position = f"{article_no}({article_title})"
    chapter = _chapter_path(article, doc)
    crumb = " > ".join(p for p in (title, chapter, position) if p)
    segs = [f"[{tag}] {crumb}"]
    if effective:
        segs.append(f"시행 {effective}")
    authority = _competent_authority(doc)
    if authority:
        # law/admrule say 소관, ordinance says 지자체 — both render naturally.
        prefix = "지자체" if doc_type == "ordinance" else "소관"
        auth_seg = f"{prefix} {authority}"
        if doc_type == "ordinance":
            # Make the 광역/기초 distinction explicit in the citation crumb.
            level = _gov_level(doc)
            if level:
                auth_seg = f"{auth_seg} ({level})"
        segs.append(auth_seg)
    return " · ".join(segs)


# --------------------------------------------------------------------------- #
# L2 (context) header.                                                          #
# --------------------------------------------------------------------------- #


def build_l2(doc: dict[str, Any], article: dict[str, Any]) -> str:
    """Build the L2 context header line by rule (09 §D-1), **never by LLM**.

    The sentence situates the chunk in its parent: parent title + kind + the
    key entity + this article's local topic (its parenthetical title / section
    name). Examples::

        이 조문은 '도로교통법'(법률, 소관 경찰청)의 일부로, '자동차등의 속도'에 관한 규정이다.
        이 판례 섹션은 대법원 '2022누50008'(선거·특별) 판결의 '판결요지'이다.

    Args:
        doc: Parsed Document dict.
        article: The article/section dict.

    Returns:
        A single non-empty L2 context line. Guaranteed non-empty (the validator
        requires an L2 line), falling back to a minimal but valid sentence when
        optional entities are missing.
    """
    doc_type = str(doc.get("doc_type") or "")
    title = _clean(doc.get("title")) or "문서"
    law_kind = _clean(doc.get("law_kind"))
    authority = _competent_authority(doc)
    article_title = _clean(article.get("title"))
    article_no = _clean(article.get("article_no"))

    if doc_type == "precedent":
        meta = doc.get("meta") or {}
        case_no = _clean(meta.get("사건번호")) or title
        court = _clean(doc.get("jurisdiction")) or _clean(meta.get("법원명"))
        case_kind = law_kind or _clean(meta.get("사건종류"))
        qualifier = " ".join(p for p in (court, f"'{case_no}'") if p).strip()
        kind_paren = f"({case_kind})" if case_kind else ""
        section = article_no or "본문"
        return (
            f"이 판례 섹션은 {qualifier}{kind_paren} 판결의 '{section}'이다."
        )

    # Legal text. Compose the parenthetical kind/authority qualifier.
    noun = _DOC_TYPE_NOUN.get(doc_type, "법령")
    quals: list[str] = []
    if law_kind:
        quals.append(law_kind)
    if authority:
        prefix = "지자체" if doc_type == "ordinance" else "소관"
        quals.append(f"{prefix} {authority}")
    paren = f"({', '.join(quals)})" if quals else ""
    topic = article_title or article_no or "해당 조문"
    return (
        f"이 조문은 '{title}'{paren} {noun}의 일부로, "
        f"'{topic}'에 관한 사항을 규정한다."
    )


# --------------------------------------------------------------------------- #
# Public entry point.                                                           #
# --------------------------------------------------------------------------- #


def build_payload(
    doc: dict[str, Any],
    article: dict[str, Any],
    *,
    part_idx: int = 0,
    kind: str = "본문",
) -> dict[str, Any]:
    """Assemble the structured payload (09 §D-2) for one chunk.

    Carries the four filter keys, parent/child linkage, and the common citation
    meta. Always includes every key in :data:`header.schema.PAYLOAD_REQUIRED`
    (a value may legitimately be ``None``, but the key is always present).

    Args:
        doc: Parsed Document dict.
        article: The article/section dict.
        part_idx: Sub-split index for over-long articles (09 §B-2).
        kind: ``"본문"`` | ``"별표"`` | ``"메타"``.

    Returns:
        The payload dict.
    """
    doc_id = _clean(doc.get("doc_id"))
    article_no = _clean(article.get("article_no"))
    trust_grade = _clean(doc.get("trust_grade")) or "A"
    payload: dict[str, Any] = {
        "doc_type": doc.get("doc_type"),
        "title": _clean(doc.get("title")),
        "jurisdiction": _clean(doc.get("jurisdiction")) or None,
        "law_kind": _clean(doc.get("law_kind")) or None,
        "article_no": article_no,
        "article_title": _clean(article.get("title")) or None,
        "chapter_path": _chapter_path(article, doc),
        "part_idx": int(part_idx),
        "effective_from": _clean(doc.get("effective_from")) or None,
        "as_of": None,
        "source_url": _clean(doc.get("source_url")) or None,
        "license": config.DEFAULT_LICENSE,
        "kind": kind,
        "trust_grade": trust_grade,
        "doc_id": doc_id,
        "parent_id": doc_id,
    }
    # Ordinance-only 광역/기초 classification (filter- and citation-friendly).
    # Always present on ordinance payloads so a caller can scope to a level or a
    # specific 기초 단체; absent (None) on other doc types.
    if doc.get("doc_type") == "ordinance":
        payload["gov_level"] = _gov_level(doc) or None
        payload["locality"] = _locality(doc) or None
    amendments = extract_amendments(article.get("text") or "")
    if amendments:
        payload["amendments"] = amendments
    # Defensive: guarantee every required key exists (None if somehow unset).
    for key in PAYLOAD_REQUIRED:
        payload.setdefault(key, None)
    return payload


def build_headers(
    doc: dict[str, Any],
    article: dict[str, Any],
    *,
    part_idx: int = 0,
    kind: str = "본문",
    body_override: str | None = None,
) -> tuple[str, dict[str, Any]]:
    """Build a chunk's embedding text and payload (BUILD CONTRACT (d)).

    This is the **single** function the chunker calls; it is the only place the
    two-layer header is assembled, so headers never drift across the codebase.

    Args:
        doc: Parsed Document dict (``ingest.schema.Document.model_dump()`` shape).
        article: One of ``doc["articles"]`` (``article_no``, ``title``, ``text``).
        part_idx: Sub-split index for over-long articles (09 §B-2); affects only
            the payload, not the header text.
        kind: Chunk kind (``"본문"`` | ``"별표"`` | ``"메타"``) for the payload.
        body_override: When the chunker has already windowed an over-long body,
            pass the (already-normalized) window text here so the same L1/L2
            header is prepended to each window. When ``None`` (default), the
            article's own ``text`` is normalized and used.

    Returns:
        ``(embed_text, payload)`` where ``embed_text`` is
        ``"<L1>\\n<L2>\\n<normalized body>"`` and ``payload`` is the §D-2 meta.
    """
    l1 = build_l1(doc, article)
    l2 = build_l2(doc, article)
    if body_override is not None:
        body = body_override.strip()
    else:
        body = normalize_body(article.get("text") or "")
    # Body may be empty for a metadata-only sentinel chunk; the two header lines
    # still make the chunk self-describing.
    embed_text = "\n".join(part for part in (l1, l2, body) if part is not None)
    payload = build_payload(doc, article, part_idx=part_idx, kind=kind)
    return embed_text, payload


__all__ = [
    "build_headers",
    "build_l1",
    "build_l2",
    "build_payload",
    "normalize_body",
    "extract_amendments",
]
